const ProductActionTypes = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',

  PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
  PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
  PRODUCT_DELETE_FAILURE: 'PRODUCT_DELETE_FAILURE',

  PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
  PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
  PRODUCT_CREATE_FAILURE: 'PRODUCT_CREATE_FAILURE',
  PRODUCT_CREATE_RESET: 'PRODUCT_CREATE_RESET',

  PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
  PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_FAILURE: 'PRODUCT_UPDATE_FAILURE',
  PRODUCT_UPDATE_RESET: 'PRODUCT_UPDATE_RESET',

  PRODUCT_CREATE_REVIEW_REQUEST: 'PRODUCT_CREATE_REVIEW_REQUEST',
  PRODUCT_CREATE_REVIEW_SUCCESS: 'PRODUCT_CREATE_REVIEW_SUCCESS',
  PRODUCT_CREATE_REVIEW_FAIL: 'PRODUCT_CREATE_REVIEW_FAIL',
  PRODUCT_CREATE_REVIEW_RESET: 'PRODUCT_CREATE_REVIEW_RESET',

  PRODUCTREVIEW_DELETE_REQUEST: 'PRODUCTREVIEW_DELETE_REQUEST',
  PRODUCTREVIEW_DELETE_SUCCESS: 'PRODUCTREVIEW_DELETE_SUCCESS',
  PRODUCTREVIEW_DELETE_FAILURE: 'PRODUCTREVIEW_DELETE_FAILURE',

  PRODUCT_TOP_REQUEST: 'PRODUCT_TOP_REQUEST',
  PRODUCT_TOP_SUCCESS: 'PRODUCT_TOP_SUCCESS',
  PRODUCT_TOP_FAIL: 'PRODUCT_TOP_FAIL',

  PRODUCT_STOCK_REQUEST: 'PRODUCT_STOCK_REQUEST',
  PRODUCT_STOCK_SUCCESS: 'PRODUCT_STOCK_SUCCESS',
  PRODUCT_STOCK_FAIL: 'PRODUCT_STOCK_FAIL',
  
  
  PRODUCT_COUNT_REQUEST: 'PRODUCT_COUNT_REQUEST',
  PRODUCT_COUNT_SUCCESS: 'PRODUCT_COUNT_SUCCESS',
  PRODUCT_COUNT_FAIL: 'PRODUCT_COUNT_FAIL',
  
  
  PRODUCT_EXPENSE_REQUEST: 'PRODUCT_EXPENSE_REQUEST',
  PRODUCT_EXPENSE_SUCCESS: 'PRODUCT_EXPENSE_SUCCESS',
  PRODUCT_EXPENSE_FAIL: 'PRODUCT_EXPENSE_FAIL',

  PRODUCT_EXPENSEFORPRODUCT_REQUEST: 'PRODUCT_EXPENSEFORPRODUCT_REQUEST',
  PRODUCT_EXPENSEFORPRODUCT_SUCCESS: 'PRODUCT_EXPENSEFORPRODUCT_SUCCESS',
  PRODUCT_EXPENSEFORPRODUCT_FAIL: 'PRODUCT_EXPENSEFORPRODUCT_FAIL',

};

export default ProductActionTypes;
